export const CHATIFY_MESSAGE_SEND = 'CHATIFY_MESSAGE_SEND';
export const CHATIFY_MESSAGE_UPVOTE = 'CHATIFY_MESSAGE_UPVOTE';

export const CHATIFY_CHANNEL_ADD = 'CHATIFY_CHANNEL_ADD';


export const CHATIFY_CHANNEL_ADD_STARTED = 'CHATIFY_CHANNEL_ADD_STARTED';
export const CHATIFY_CHANNEL_ADD_SUCCESS = 'CHATIFY_CHANNEL_ADD_SUCCESS';
export const CHATIFY_CHANNEL_ADD_FAILURE = 'CHATIFY_CHANNEL_ADD_FAILURE';

export const CHATIFY_USER_LOGIN_STARTED = 'CHATIFY_USER_LOGIN_STARTED';
export const CHATIFY_USER_LOGIN_SUCCESS = 'CHATIFY_USER_LOGIN_SUCCESS';
export const CHATIFY_USER_LOGIN_FAILURE = 'CHATIFY_USER_LOGIN_FAILURE';

export const CHATIFY_RECEIVE_TOKEN = 'CHATIFY_RECEIVE_TOKEN';
export const CHATIFY_INVALIDATE_TOKEN = 'CHATIFY_INVALIDATE_TOKEN';

export const CHATIFY_USER_REGISTER_STARTED = 'CHATIFY_USER_REGISTER_STARTED';
export const CHATIFY_USER_REGISTER_SUCCESS = 'CHATIFY_USER_REGISTER_SUCCESS';
export const CHATIFY_USER_REGISTER_FAILURE = 'CHATIFY_USER_REGISTER_FAILURE';

export const CHATIFY_USER_LOGOUT = 'CHATIFY_USER_LOGOUT';
