export const CHATIFY_MESSAGE_SEND = 'CHATIFY_MESSAGE_SEND';
export const CHATIFY_MESSAGE_UPVOTE = 'CHATIFY_MESSAGE_UPVOTE';

export const CHATIFY_CHANNEL_ADD = 'CHATIFY_CHANNEL_ADD';


export const CHATIFY_CHANNEL_ADD_STARTED = 'CHATIFY_CHANNEL_ADD_STARTED';
export const CHATIFY_CHANNEL_ADD_SUCCESS = 'CHATIFY_CHANNEL_ADD_SUCCESS';
