export const CHATIFY_MESSAGE_SEND_STARTED = 'CHATIFY_MESSAGE_SEND_STARTED';
export const CHATIFY_MESSAGE_SEND_SUCCESS = 'CHATIFY_MESSAGE_SEND_SUCCESS';
export const CHATIFY_MESSAGE_SEND_FAILURE = 'CHATIFY_MESSAGE_SEND_FAILURE';

export const CHATIFY_MESSAGE_DELETE_STARTED = 'CHATIFY_MESSAGE_DELETE_STARTED';
export const CHATIFY_MESSAGE_DELETE_SUCCESS = 'CHATIFY_MESSAGE_DELETE_SUCCESS';
export const CHATIFY_MESSAGE_DELETE_FAILURE = 'CHATIFY_MESSAGE_DELETE_FAILURE';

export const CHATIFY_MESSAGE_UPVOTE_STARTED = 'CHATIFY_MESSAGE_UPVOTE_STARTED';
export const CHATIFY_MESSAGE_UPVOTE_SUCCESS = 'CHATIFY_MESSAGE_UPVOTE_SUCCESS';
export const CHATIFY_MESSAGE_UPVOTE_FAILURE = 'CHATIFY_MESSAGE_UPVOTE_FAILURE';

export const CHATIFY_CHANNEL_ADD = 'CHATIFY_CHANNEL_ADD';

export const CHATIFY_CHANNEL_ADD_STARTED = 'CHATIFY_CHANNEL_ADD_STARTED';
export const CHATIFY_CHANNEL_ADD_SUCCESS = 'CHATIFY_CHANNEL_ADD_SUCCESS';
export const CHATIFY_CHANNEL_ADD_FAILURE = 'CHATIFY_CHANNEL_ADD_FAILURE';

export const CHATIFY_USER_LOGIN_STARTED = 'CHATIFY_USER_LOGIN_STARTED';
export const CHATIFY_USER_LOGIN_SUCCESS = 'CHATIFY_USER_LOGIN_SUCCESS';
export const CHATIFY_USER_LOGIN_FAILURE = 'CHATIFY_USER_LOGIN_FAILURE';

export const CHATIFY_RECEIVE_TOKEN = 'CHATIFY_RECEIVE_TOKEN';
export const CHATIFY_INVALIDATE_TOKEN = 'CHATIFY_INVALIDATE_TOKEN';

export const CHATIFY_USER_REGISTER_STARTED = 'CHATIFY_USER_REGISTER_STARTED';
export const CHATIFY_USER_REGISTER_SUCCESS = 'CHATIFY_USER_REGISTER_SUCCESS';
export const CHATIFY_USER_REGISTER_FAILURE = 'CHATIFY_USER_REGISTER_FAILURE';

export const CHATIFY_USER_LOGOUT = 'CHATIFY_USER_LOGOUT';

export const CHATIFY_PROFILE_UPDATE_USER_DETAILS_STARTED = 'CHATIFY_PROFILE_UPDATE_USER_DETAILS_STARTED';
export const CHATIFY_PROFILE_UPDATE_USER_DETAILS_SUCCESS = 'CHATIFY_PROFILE_UPDATE_USER_DETAILS_SUCCESS';
export const CHATIFY_PROFILE_UPDATE_USER_DETAILS_FAILED = 'CHATIFY_PROFILE_UPDATE_USER_DETAILS_FAILED';

export const CHATIFY_PROFILE_FETCHING_USER_DETAILS_STARTED = 'CHATIFY_PROFILE_FETCHING_USER_DETAILS_STARTED';
export const CHATIFY_PROFILE_FETCHING_USER_DETAILS_SUCCESS = 'CHATIFY_PROFILE_FETCHING_USER_DETAILS_SUCCESS';
export const CHATIFY_PROFILE_FETCHING_USER_DETAILS_FAILED = 'CHATIFY_PROFILE_FETCHING_USER_DETAILS_FAILED';

export const CHATIFY_PROFILE_UPLOAD_AVATAR_STARTED = 'CHATIFY_PROFILE_UPLOAD_AVATAR_STARTED';
export const CHATIFY_PROFILE_UPLOAD_AVATAR_SUCCESS = 'CHATIFY_PROFILE_UPLOAD_AVATAR_SUCCESS';
export const CHATIFY_PROFILE_UPLOAD_AVATAR_FAILED = 'CHATIFY_PROFILE_UPLOAD_AVATAR_FAILED';

export const CHATIFY_PROFILE_FETCH_AVATAR_STARTED = 'CHATIFY_PROFILE_FETCH_AVATAR_STARTED';
export const CHATIFY_PROFILE_FETCH_AVATAR_SUCCESS = 'CHATIFY_PROFILE_FETCH_AVATAR_SUCCESS';
export const CHATIFY_PROFILE_FETCH_AVATAR_FAILED = 'CHATIFY_PROFILE_FETCH_AVATAR_FAILED';
